# Grid
GRID_SIZE = 4
CELL_SIZE = 100
WIDTH = HEIGHT = GRID_SIZE * CELL_SIZE

# States
START_STATE = (0, 0)
TREASURE_STATE = (3, 3)
TRAP_STATE = (1, 2)

# Actions
ACTIONS = [0, 1, 2, 3]  # UP, DOWN, LEFT, RIGHT

# Rewards
MOVE_REWARD = 1
INVALID_MOVE_REWARD = -1
TREASURE_REWARD = 10
TRAP_REWARD = -10

# Q-learning parameters
ALPHA = 0.1
GAMMA = 0.9
EPSILON = 0.3
EPISODES = 300
